name: Quokka

on:
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches: 
      - main
      - develop

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set environment variables
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: echo "Environment variables set"

    - name: Create quokka-credentials.json
      run: |
        mkdir -p db
        echo "${{ secrets.QUOKKA_CREDENTIALS }}" > db/quokka-credentials.json

    # Uncomment the following lines if you want to run flake8 linting
    #- name: Lint with flake8
    #  run: |
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: pytest
